pipeline {
    agent { label "momo_server"}
    stages {
        stage("clean") {
            steps {
                sh """
                    echo "Removing old files..."
                    rm -r * || exit 0
                    echo "Stoping old files..."
                    docker stop nappuccino-app || exit 0 
                    echo "Clean up done."
                """
            }
        }
        stage("build") {
            steps {
                sh """
                    git clone https://github.com/AymericBdy/Nappuccino
                    cd Nappuccino/server
                    mkdir certs || exit 0
                    cp /etc/letsencrypt/live/valentin.molina.pro/fullchain.pem certs/server.cert
                    cp /etc/letsencrypt/live/valentin.molina.pro/privkey.pem certs/server.key
                    mkdir properties || exit 0
                    cp /home/jenkins/Nappuccino-data/properties/bdd.json properties/bdd.json
                    git checkout backend
                    docker build . -t nappuccino
                """
            }
        }
        stage("run") {
            steps {
                sh """
                    docker run --rm -p 3000:3000 -d --name nappuccino-app  nappuccino
                """
            }
        }
    }
}